-- CreateTable
CREATE TABLE "Pendaftar" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" TEXT NOT NULL DEFAULT 'Menunggu',
    "noPendaftaran" TEXT,
    "jenjang" TEXT NOT NULL,
    "nama" TEXT NOT NULL,
    "jenisKelamin" TEXT NOT NULL,
    "tempatLahir" TEXT NOT NULL,
    "tanggalLahir" DATETIME NOT NULL,
    "nik" TEXT NOT NULL,
    "anakKe" INTEGER,
    "jumlahSaudara" INTEGER,
    "agama" TEXT,
    "tinggiBadan" REAL,
    "beratBadan" REAL,
    "alamat" TEXT,
    "dusun" TEXT,
    "desa" TEXT,
    "kecamatan" TEXT,
    "kabupaten" TEXT,
    "noHpOrtu" TEXT,
    "sekolahAsal" TEXT,
    "transportasi" TEXT,
    "namaAyah" TEXT,
    "tempatLahirAyah" TEXT,
    "alamatAyah" TEXT,
    "tahunLahirAyah" INTEGER,
    "pendidikanAyah" TEXT,
    "pekerjaanAyah" TEXT,
    "penghasilanAyah" TEXT,
    "namaIbu" TEXT,
    "tempatLahirIbu" TEXT,
    "alamatIbu" TEXT,
    "tahunLahirIbu" INTEGER,
    "pendidikanIbu" TEXT,
    "pekerjaanIbu" TEXT,
    "penghasilanIbu" TEXT,
    "ijazah" TEXT,
    "kk" TEXT,
    "akta" TEXT,
    "ktp" TEXT
);

-- CreateIndex
CREATE UNIQUE INDEX "Pendaftar_noPendaftaran_key" ON "Pendaftar"("noPendaftaran");
